#pragma once
class Card
{
	enum card { 
		AS_ESPADAS, AS_COPAS, AS_PAUS, AS_OUROS,
		DOIS_ESPADAS, DOIS_COPAS, DOIS_PAUS, DOIS_OUROS,
		TRES_ESPADAS, TRES_COPAS, TRES_PAUS, TRES_OUROS,
		QUATRO_ESPADAS, QUATRO_COPAS, QUATRO_PAUS, QUATRO_OUROS,
		CINCO_ESPADAS, CINCO_COPAS, CINCO_PAUS, CINCO_OUROS,
		SEIS_ESPADAS, SEIS_COPAS, SEIS_PAUS, SEIS_OUROS,
		SETE_ESPADAS, SETE_COPAS, SETE_PAUS, SETE_OUROS,
		OITO_ESPADAS, OITO_COPAS, OITO_PAUS, OITO_OUROS,
		NOVE_ESPADAS, NOVE_COPAS, NOVE_PAUS, NOVE_OUROS,
		DEZ_ESPADAS, DEZ_COPAS, DEZ_PAUS, DEZ_OUROS,
		DAMA_ESPADAS, DAMA_COPAS, DAMA_PAUS, DAMA_OUROS,
		VALETE_ESPADAS, VALETE_COPAS, VALETE_PAUS, VALETE_OUROS,
		REI_ESPADAS, REI_COPAS, REI_PAUS, REI_OUROS
	};
public:
	Card();
	~Card();
};

